apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: robomart
spec:
  selector:
    project: {{ .Values.deployment.project }}
    component: {{ .Values.deployment.component }}
    tier: backend
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port
